name: duolibras
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  firebase_core: 
  firebase_auth: 
  cloud_firestore: 
  firebase_storage: ^10.0.3 
  cupertino_icons: ^1.0.2
  google_sign_in: ^5.0.7
  sign_in_with_apple: ^3.0.0
  camera: ^0.9.2+2
  firebase_dynamic_links: ^2.0.9
  custom_navigator:
    git:
      url: https://github.com/kjawadDeveloper/Custom-navigator.git
  rxdart: ^0.27.2
  provider: ^6.0.0
  confetti: ^0.5.5
  get_it: ^7.2.0
  tuple: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  modal_bottom_sheet: ^2.0.0
  download_assets: ^2.0.0
  image: ^3.0.8
  shared_preferences: ^2.0.8
  uuid: ^3.0.5
  flutter_launcher_icons: ^0.9.2
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.2.1
  collection: ^1.15.0
  permission_handler:
  audioplayers:
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icons/icon.png"
  image_path_android: "assets/icons/icon.png"
  adaptive_icon_background: "assets/icons/background.png"
  adaptive_icon_foreground: "assets/icons/foreground.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/feedbackScreen/
    - assets/images/happyFace.png
    - lib/Services/Mock/
    - assets/images/nextExerciseArrow/
    - assets/images/navBar/
    - assets/images/tabBar/
    - assets/images/profileScreen/
    - assets/images/google_icon.png
    - assets/images/background_login/
    - assets/images/background_home/
    - assets/images/moduleWidget/
    - assets/successSound.wav
    - assets/errorSound.wav

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
